modLoader = "kotlinforforge"
loaderVersion = "${versions.kotlin_neoforge_range}"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
logoFile = "${modId}.png"
credits = "${credits}"
authors = "${modAuthor}"
description = '''${description}'''

[[mixins]]
config = "${modId}.mixins.json"

[[mixins]]
config = "${modId}.neoforge.mixins.json"

[[dependencies."${modId}"]]
modId = "neoforge"
type = "required"
versionRange = "${versions.neoforge_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "minecraft"
type = "required"
versionRange = "${versions.minecraft_range}"
ordering = "NONE"
side = "BOTH"
